#!/usr/bin/env python3
"""
Convert existing ONNX model to TFLite
======================================

Uses the already-generated stress_model.onnx to create TFLite model.
This skips the PyTorch → ONNX step since we already have the ONNX file.

Usage:
    python3 onnx_to_tflite.py
"""

import os
import sys
import numpy as np
from pathlib import Path

# Configuration
ONNX_PATH = Path(__file__).parent / "model_output/stress_model.onnx"
OUTPUT_DIR = Path(__file__).parent / "model_output"
TF_MODEL_PATH = OUTPUT_DIR / "tf_model"
TFLITE_PATH = OUTPUT_DIR / "stress_model.tflite"
TFLITE_QUANT_PATH = OUTPUT_DIR / "stress_model_quant.tflite"
C_HEADER_PATH = Path(__file__).parent / "components/cnn_inference/include/stress_model_data.h"

print("=" * 80)
print("ONNX to TFLite Converter")
print("=" * 80)

if not ONNX_PATH.exists():
    print(f"❌ ERROR: ONNX model not found: {ONNX_PATH}")
    sys.exit(1)

print(f"\nInput:  {ONNX_PATH} ({ONNX_PATH.stat().st_size / 1024:.2f} KB)")
print(f"Output: {TFLITE_QUANT_PATH}")

# Step 1: Convert ONNX to TensorFlow
print("\n" + "=" * 80)
print("Step 1: Converting ONNX to TensorFlow")
print("=" * 80)

try:
    import onnx2tf
    
    print("Running onnx2tf conversion...")
    onnx2tf.convert(
        input_onnx_file_path=str(ONNX_PATH),
        output_folder_path=str(TF_MODEL_PATH),
        copy_onnx_input_output_names_to_tflite=True,
        non_verbose=True,
    )
    print(f"✅ TensorFlow model saved: {TF_MODEL_PATH}")
    
except Exception as e:
    print(f"❌ ERROR during ONNX to TensorFlow conversion: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

# Step 2: Convert TensorFlow to TFLite
print("\n" + "=" * 80)
print("Step 2: Converting TensorFlow to TFLite")
print("=" * 80)

try:
    import tensorflow as tf
    
    # Load TensorFlow model
    print("Loading TensorFlow SavedModel...")
    converter = tf.lite.TFLiteConverter.from_saved_model(str(TF_MODEL_PATH))
    
    # Convert to float32 TFLite (baseline)
    print("\n2a. Converting to Float32 TFLite...")
    tflite_model = converter.convert()
    with open(TFLITE_PATH, 'wb') as f:
        f.write(tflite_model)
    print(f"✅ Float32 TFLite saved: {TFLITE_PATH} ({len(tflite_model) / 1024:.2f} KB)")
    
    # Convert to INT8 quantized TFLite
    print("\n2b. Converting to INT8 Quantized TFLite...")
    converter = tf.lite.TFLiteConverter.from_saved_model(str(TF_MODEL_PATH))
    
    # Apply optimizations
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    
    # Representative dataset for quantization calibration
    def representative_dataset():
        for _ in range(100):
            # Generate random normalized signals
            data = np.random.randn(1, 4, 240).astype(np.float32)
            yield [data]
    
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.float32  # Still accept float input
    converter.inference_output_type = tf.float32  # Still output float
    
    tflite_quant_model = converter.convert()
    with open(TFLITE_QUANT_PATH, 'wb') as f:
        f.write(tflite_quant_model)
    
    print(f"✅ INT8 Quantized TFLite saved: {TFLITE_QUANT_PATH} ({len(tflite_quant_model) / 1024:.2f} KB)")
    
    # Calculate compression ratio
    compression = (1 - len(tflite_quant_model) / len(tflite_model)) * 100
    print(f"\n   Compression: {compression:.1f}% smaller")
    
except Exception as e:
    print(f"❌ ERROR during TFLite conversion: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

# Step 3: Generate C header file
print("\n" + "=" * 80)
print("Step 3: Generating C Header File")
print("=" * 80)

try:
    # Read quantized TFLite model
    with open(TFLITE_QUANT_PATH, 'rb') as f:
        model_data = f.read()
    
    # Create C header directory
    C_HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
    
    # Generate header content
    header_content = f"""/**
 * @file stress_model_data.h
 * @brief Embedded TensorFlow Lite model for stress detection
 * 
 * Model size: {len(model_data)} bytes ({len(model_data) / 1024:.2f} KB)
 * 
 * Input shape: (1, 4, 240) - [ACC_MAG, BVP, EDA, TEMP]
 * Output shape: (1, 1) - Stress probability [0.0-1.0]
 * 
 * Quantization: INT8 (weights and activations)
 * Input/Output type: FLOAT32
 * 
 * Generated by: onnx_to_tflite.py
 */

#ifndef STRESS_MODEL_DATA_H
#define STRESS_MODEL_DATA_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

// Model metadata
#define STRESS_MODEL_SIZE {len(model_data)}
#define STRESS_MODEL_INPUT_CHANNELS 4
#define STRESS_MODEL_INPUT_SAMPLES 240
#define STRESS_MODEL_OUTPUT_SIZE 1

// Embedded model data
extern const unsigned char g_stress_model_data[];
extern const unsigned int g_stress_model_data_len;

#ifdef __cplusplus
}}
#endif

#endif // STRESS_MODEL_DATA_H
"""
    
    # Write header file
    with open(C_HEADER_PATH, 'w') as f:
        f.write(header_content)
    
    # Generate C source file with model data
    c_source_path = C_HEADER_PATH.parent.parent / "stress_model_data.c"
    
    with open(c_source_path, 'w') as f:
        f.write('#include "stress_model_data.h"\n\n')
        f.write('// Embedded TensorFlow Lite model data\n')
        f.write('const unsigned char g_stress_model_data[] __attribute__((aligned(16))) = {\n')
        
        # Write model bytes (16 per line)
        for i in range(0, len(model_data), 16):
            chunk = model_data[i:i+16]
            hex_values = ', '.join(f'0x{b:02x}' for b in chunk)
            f.write(f'  {hex_values},\n')
        
        f.write('};\n\n')
        f.write(f'const unsigned int g_stress_model_data_len = {len(model_data)};\n')
    
    print(f"✅ C header generated: {C_HEADER_PATH}")
    print(f"✅ C source generated: {c_source_path}")
    print(f"   Model size: {len(model_data)} bytes ({len(model_data) / 1024:.2f} KB)")
    
except Exception as e:
    print(f"❌ ERROR generating C files: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

# Step 4: Validate TFLite model
print("\n" + "=" * 80)
print("Step 4: Validating TFLite Model")
print("=" * 80)

try:
    import tensorflow as tf
    
    # Load interpreter
    interpreter = tf.lite.Interpreter(model_path=str(TFLITE_QUANT_PATH))
    interpreter.allocate_tensors()
    
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    print(f"\nInput tensor:")
    print(f"  Shape: {input_details[0]['shape']}")
    print(f"  Type: {input_details[0]['dtype']}")
    
    print(f"\nOutput tensor:")
    print(f"  Shape: {output_details[0]['shape']}")
    print(f"  Type: {output_details[0]['dtype']}")
    
    # Test inference
    test_input = np.random.randn(1, 4, 240).astype(np.float32)
    interpreter.set_tensor(input_details[0]['index'], test_input)
    interpreter.invoke()
    output = interpreter.get_tensor(output_details[0]['index'])
    
    print(f"\nTest inference:")
    print(f"  Input shape: {test_input.shape}")
    print(f"  Output: {output[0, 0]:.6f}")
    print(f"  Output range: [0.0, 1.0] ✅" if 0 <= output[0, 0] <= 1 else "  Output range: ERROR ❌")
    
    print(f"\n✅ Model validation successful")
    
except Exception as e:
    print(f"❌ ERROR validating model: {e}")
    import traceback
    traceback.print_exc()

# Success!
print("\n" + "=" * 80)
print("✅ CONVERSION COMPLETE!")
print("=" * 80)
print(f"\nFiles generated:")
print(f"  TFLite model:  {TFLITE_QUANT_PATH}")
print(f"  C header:      {C_HEADER_PATH}")
print(f"  C source:      {c_source_path}")
print(f"\nNext steps:")
print(f"  1. Create cnn_inference component in ESP-IDF")
print(f"  2. Integrate TFLite Micro runtime")
print(f"  3. Test on ESP32-S3 hardware")
